# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-exec" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "880b1070c910bed23f0aceffe42888f47d5fad646a9955e0da4bcaa88d469fc0"
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d70688d5a8a5bf19bf1950d022b3a1b1696442612b931965594fe1a45a8b1ae"
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "500a8b5716ed4bad0f00e73b7fff87317aa61022ea0063994339e29f2f805baa"
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fbd0900bc1be43887ee87fbc4a0f85779e4feff5cdfe292ebe10d93c2317a97e"
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Linux_x86_64.tar.gz"
    end
  end

  name "env-exec"
  desc "The Environment variable executor"
  homepage "https://github.com/polarn/env-exec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-exec"

  # No zap stanza required
end
