# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-exec" do
  name "env-exec"
  desc "The Environment variable executor"
  homepage "https://github.com/polarn/env-exec"
  version "0.18.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-exec"

  on_macos do
    on_intel do
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Darwin_x86_64.tar.gz"
      sha256 "1b77e8cb215c6b7725b1015a9f6c178a474ace3c695df96ceceea946742abca2"
    end
    on_arm do
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Darwin_arm64.tar.gz"
      sha256 "4eb298b435f4c943ff1e47c3afed6fea2b08ba67b3d18130e8249edfb563a1b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Linux_x86_64.tar.gz"
      sha256 "928e9441fecfac5ce2b627ec27476b5dfa8916f915e99a4915d44144e468ba8d"
    end
    on_arm do
      url "https://github.com/polarn/env-exec/releases/download/#{version}/env-exec_Linux_arm64.tar.gz"
      sha256 "cf375326d0a199b662ec7da87cb758a6fd80ae11dd56c81ba014b5633c7d11fc"
    end
  end

  # No zap stanza required
end
