# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnvExec < Formula
  desc "The Environment variable executor"
  homepage "https://github.com/polarn/env-exec"
  version "0.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/polarn/env-exec/releases/download/0.13.0/env-exec_Darwin_x86_64.tar.gz"
      sha256 "96122abe2ef1a7d2bf0f9a8ea05622a868aeaad5794682acf38dc60047529c6f"

      def install
        bin.install "env-exec"

        generate_completions_from_executable(bin/"env-exec", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/polarn/env-exec/releases/download/0.13.0/env-exec_Darwin_arm64.tar.gz"
      sha256 "117721def64f2a3a0b821135f7b81e2743925b4b20b6850537b5873d9449c07f"

      def install
        bin.install "env-exec"

        generate_completions_from_executable(bin/"env-exec", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/polarn/env-exec/releases/download/0.13.0/env-exec_Linux_x86_64.tar.gz"
        sha256 "35a219311f49799b36950f4786134d18d0a2952257bc28393a0f6b6e3c78d039"

        def install
          bin.install "env-exec"

          generate_completions_from_executable(bin/"env-exec", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/polarn/env-exec/releases/download/0.13.0/env-exec_Linux_arm64.tar.gz"
        sha256 "21804d51f843f9c16eac9dcc423b5947c99296ebb21bec37dc618653b58ef4ee"

        def install
          bin.install "env-exec"

          generate_completions_from_executable(bin/"env-exec", "completion")
        end
      end
    end
  end

  test do
    system "echo Sorry, no test yet"
  end
end
